baseURL = 'https://hugorouillard.dev/'
locale = 'en-us'
title = 'Hugo Rouillard'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 5

[[menus.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 10

[[menus.main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 20

[params]
  description = 'Things I’ve built, things I’ve written, and whatever else has caught my attention.'
  github = 'https://github.com/hugorouillard'
  linkedin = 'https://www.linkedin.com/in/rouillard-hugo/'
